name: update

on:
  workflow_dispatch:

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run github:Mic92/nix-update -- k0s_1_32 --flake --use-update-script
      - uses: peter-evans/create-pull-request@v7
        with:
            commit-message: Update dependencies
            title: 'feat(update): k0s_1_32'
            branch: update-dependencies-1-32
