name: update

on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  k0s-version-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: compute k0s version matrix
        id: set-matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#packages.x86_64-linux' | jq -cr 'keys | map(select(contains("k0s_")))')"
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"

  check-for-updates:
    runs-on: ubuntu-latest
    needs: k0s-version-matrix
    strategy:
      fail-fast: false
      matrix:
        k0s-version: ${{ fromJson(needs.k0s-version-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            filter-syscalls = false
            experimental-features = nix-command flakes
      - name: nix-update
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version="${{ matrix.k0s-version }}"
          filename="k0s/${version#k0s_}.nix"
          nix run github:Mic92/nix-update -- --flake --use-update-script --override-filename ${filename} --write-commit-message commit.md ${version}
      - name: commit message
        id: commit-message
        run: |
          if [ ! -f commit.md ]; then
            echo "No updates found." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi
          echo "message<<EOF" >> $GITHUB_OUTPUT
          cat commit.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          rm commit.md

      - uses: peter-evans/create-pull-request@v7
        if: ${{ steps.commit-message.outputs.message }}
        with:
          commit-message: ${{ steps.commit-message.outputs.message }}
          title: ${{ steps.commit-message.outputs.message }}
          body: |
            This PR was automatically generated by the k0s nix update workflow.

            See workflow run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          branch: update-${{ matrix.k0s-version }}
